name: paytm_payments
description: Paytm Payments Flutter SDK
version: 0.0.1
author: Apoorv Jain <ajax8732@gmail.com>
homepage: https://github.com/apoorv9496/paytm_payments

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: xyz.ajax.paytm_payments
    pluginClass: PaytmPaymentsPlugin